package output

import (
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strings"

	"cf-anycast-router/internal/config"
)

type ActiveRoute struct {
	IP        string
	Domain    string
	Name      string
	Port      int
	SNI       string
	Score     float64
	Carrier   string
	POP       string
	Extra     map[string]string
	Decision  string
	TraceHost string
}

func RenderAll(outputs []config.OutputConfig, active ActiveRoute) ([]string, error) {
	written := make([]string, 0, len(outputs))
	for _, out := range outputs {
		route := active
		if out.Domain != "" {
			route.Domain = out.Domain
		}
		if out.Name != "" {
			route.Name = out.Name
		}
		if out.Port > 0 {
			route.Port = out.Port
		}
		if out.SNI != "" {
			route.SNI = out.SNI
		}
		if len(out.Extra) > 0 {
			route.Extra = out.Extra
		}
		text, err := Render(out.Type, route)
		if err != nil {
			return written, err
		}
		if out.Path == "" {
			return written, fmt.Errorf("output %s path is required", out.Type)
		}
		if err := os.MkdirAll(filepath.Dir(out.Path), 0755); err != nil {
			return written, err
		}
		if err := os.WriteFile(out.Path, []byte(text), 0644); err != nil {
			return written, err
		}
		written = append(written, out.Path)
	}
	return written, nil
}

func Render(kind string, r ActiveRoute) (string, error) {
	if r.Domain == "" {
		r.Domain = r.TraceHost
	}
	if r.Name == "" {
		r.Name = "cf-anycast-active"
	}
	if r.Port == 0 {
		r.Port = 443
	}
	if r.SNI == "" {
		r.SNI = r.Domain
	}
	header := fmt.Sprintf("# generated by cf-anycast-router\n# active=%s pop=%s carrier=%s score=%.2f\n", r.IP, r.POP, r.Carrier, r.Score)
	switch strings.ToLower(strings.TrimSpace(kind)) {
	case "hosts":
		return header + fmt.Sprintf("%s %s\n", r.IP, r.Domain), nil
	case "dnsmasq":
		return header + fmt.Sprintf("address=/%s/%s\n", r.Domain, r.IP), nil
	case "adguard", "adguard_rewrite":
		return header + fmt.Sprintf("rewrites:\n  - domain: %s\n    answer: %s\n", r.Domain, r.IP), nil
	case "smartdns":
		return header + fmt.Sprintf("address /%s/%s\n", r.Domain, r.IP), nil
	case "coredns":
		return header + fmt.Sprintf("%s:53 {\n    hosts {\n        %s %s\n        fallthrough\n    }\n}\n", r.Domain, r.IP, r.Domain), nil
	case "nginx", "nginx_stream":
		return header + fmt.Sprintf("upstream cf_anycast_active {\n    server %s:%d max_fails=2 fail_timeout=10s;\n}\n", r.IP, r.Port), nil
	case "clash", "clash_provider":
		return header + clashProvider(r), nil
	case "sing-box", "sing_box", "sing-box-outbound", "sing_box_outbound":
		return header + singBoxOutbound(r), nil
	default:
		return "", fmt.Errorf("unknown output type %q", kind)
	}
}

func clashProvider(r ActiveRoute) string {
	extra := yamlMap(r.Extra, "    ")
	if extra == "" {
		extra = "    type: trojan\n    password: CHANGE_ME\n"
	}
	return fmt.Sprintf("proxies:\n  - name: %q\n    server: %s\n    port: %d\n    sni: %s\n%s", r.Name, r.IP, r.Port, r.SNI, extra)
}

func singBoxOutbound(r ActiveRoute) string {
	extra := jsonMap(r.Extra, "    ")
	if extra == "" {
		extra = "    \"type\": \"trojan\",\n    \"password\": \"CHANGE_ME\",\n"
	}
	return fmt.Sprintf("{\n%s    \"tag\": %q,\n    \"server\": %q,\n    \"server_port\": %d,\n    \"tls\": { \"enabled\": true, \"server_name\": %q }\n}\n", extra, r.Name, r.IP, r.Port, r.SNI)
}

func yamlMap(m map[string]string, indent string) string {
	if len(m) == 0 {
		return ""
	}
	keys := make([]string, 0, len(m))
	for k := range m {
		keys = append(keys, k)
	}
	sort.Strings(keys)
	var b strings.Builder
	for _, k := range keys {
		b.WriteString(fmt.Sprintf("%s%s: %s\n", indent, k, quoteIfNeeded(m[k])))
	}
	return b.String()
}

func jsonMap(m map[string]string, indent string) string {
	if len(m) == 0 {
		return ""
	}
	keys := make([]string, 0, len(m))
	for k := range m {
		keys = append(keys, k)
	}
	sort.Strings(keys)
	var b strings.Builder
	for _, k := range keys {
		b.WriteString(fmt.Sprintf("%s%q: %q,\n", indent, k, m[k]))
	}
	return b.String()
}

func quoteIfNeeded(v string) string {
	if v == "" {
		return "\"\""
	}
	if strings.ContainsAny(v, ":#{}[],&* !") {
		return fmt.Sprintf("%q", v)
	}
	return v
}
